from typing import Any, Dict

from app.services.world.appearance import default_appearance_profile
from app.services.world.state_defaults import default_character_modifiers


def blank_character_state(slot_name: str) -> Dict[str, Any]:
    return {
        "slot_id": slot_name,
        "bio": {
            "name": "",
            "gender": "",
            "age": "",
            "age_years": 0,
            "age_stage": "young",
            "earth_life": "",
            "personality": [],
            "goal": "",
            "isekai_price": "",
            "background_tags": [],
            "strength": "",
            "weakness": "",
            "focus": "",
            "earth_items": [],
            "signature_item": "",
        },
        "scene_id": "",
        "appearance": default_appearance_profile(),
        "appearance_history": [],
        "class_current": None,
        "faction_memberships": [],
        "aging": {
            "arrival_absolute_day": 1,
            "days_since_arrival": 0,
            "last_aged_absolute_day": 1,
            "age_effects_applied": [],
        },
        "modifiers": default_character_modifiers(),
        "resources": {
            "hp": {"current": 10, "base_max": 10, "bonus_max": 0, "max": 10},
            "stamina": {"current": 10, "base_max": 10, "bonus_max": 0, "max": 10},
            "aether": {"current": 5, "base_max": 5, "bonus_max": 0, "max": 5},
            "stress": {"current": 0, "base_max": 10, "bonus_max": 0, "max": 10},
            "corruption": {"current": 0, "base_max": 10, "bonus_max": 0, "max": 10},
            "wounds": {"current": 0, "base_max": 3, "bonus_max": 0, "max": 3},
        },
        "hp_current": 10,
        "hp_max": 10,
        "sta_current": 10,
        "sta_max": 10,
        "res_current": 5,
        "res_max": 5,
        "element_affinities": [],
        "element_resistances": [],
        "element_weaknesses": [],
        "carry_current": 0,
        "carry_max": 10,
        "level": 1,
        "xp_total": 0,
        "xp_current": 0,
        "xp_to_next": 120,
        "recent_progression_events": [],
        "class_path_seeds": [],
        "attributes": {
            "str": 0,
            "dex": 0,
            "con": 0,
            "int": 0,
            "wis": 0,
            "cha": 0,
            "luck": 0,
        },
        "derived": {
            "defense": 10,
            "armor": 0,
            "attack_rating_mainhand": 0,
            "attack_rating_offhand": 0,
            "initiative": 0,
            "carry_limit": 10,
            "carry_weight": 0,
            "encumbrance_state": "normal",
            "age_modifiers": {
                "stage": "young",
                "resource_deltas": {"hp_max": 0, "stamina_max": 0},
                "skill_bonuses": {},
                "notes": [],
            },
            "resistances": {
                "physical": 0,
                "fire": 0,
                "cold": 0,
                "lightning": 0,
                "poison": 0,
                "bleed": 0,
                "shadow": 0,
                "holy": 0,
                "curse": 0,
                "fear": 0,
            },
            "combat_flags": {
                "in_combat": False,
                "downed": False,
                "can_act": True,
            },
        },
        "skills": {},
        "abilities": [],
        "effects": [],
        "inventory": {
            "items": [],
            "quick_slots": {
                "slot_1": "",
                "slot_2": "",
                "slot_3": "",
                "slot_4": "",
            },
        },
        "equipment": {
            "weapon": "",
            "offhand": "",
            "head": "",
            "chest": "",
            "gloves": "",
            "boots": "",
            "amulet": "",
            "ring_1": "",
            "ring_2": "",
            "trinket": "",
        },
        "progression": {
            "rank": 1,
            "xp": 0,
            "next_xp": 100,
            "system_level": 1,
            "system_xp": 0,
            "next_system_xp": 100,
            "resource_name": "Aether",
            "resource_current": 5,
            "resource_max": 5,
            "system_fragments": 0,
            "system_cores": 0,
            "attribute_points": 0,
            "skill_points": 0,
            "talent_points": 0,
            "paths": [],
            "potential_cards": [],
        },
        "injuries": [],
        "scars": [],
        "journal": {
            "notes": [],
            "npc_relationships": [],
            "reputation": [],
            "personal_plotpoints": [],
        },
        # compatibility mirrors for older turns/UI
        "hp": 10,
        "stamina": 10,
        "conditions": [],
        "equip": {"weapon": "", "armor": "", "trinket": ""},
        "potential": [],
    }
