from typing import Any, Callable, Dict, List, Optional


def build_turn_record_payload(
    *,
    campaign: Dict[str, Any],
    actor: str,
    player_id: Optional[str],
    action_type: str,
    content: str,
    gm_text_display: str,
    requests_payload: List[Dict[str, Any]],
    skill_requests: List[Dict[str, Any]],
    patch: Dict[str, Any],
    narrator_patch: Dict[str, Any],
    extractor_patch: Dict[str, Any],
    canon_applied: bool,
    attribute_profile: Dict[str, Any],
    combat_resolution: Dict[str, Any],
    resource_deltas_applied: Dict[str, Any],
    progression_result: Dict[str, Any],
    canon_gate_meta: Dict[str, Any],
    npc_updates: List[Dict[str, Any]],
    codex_updates: List[Dict[str, Any]],
    updated_combat: Dict[str, Any],
    state_before: Dict[str, Any],
    state_after: Dict[str, Any],
    retry_of_turn_id: Optional[str],
    prompt_payload: Dict[str, Any],
    entity_guard: Optional[Dict[str, Any]] = None,
    make_id: Callable[[str], str],
    utc_now: Callable[[], str],
    deep_copy: Callable[[Any], Any],
    normalize_requests_payload: Callable[..., List[Dict[str, Any]]],
    is_continue_story_content: Callable[[str], bool],
) -> Dict[str, Any]:
    now = utc_now()
    combined_requests = normalize_requests_payload(requests_payload + skill_requests, default_actor=actor)
    input_text_display = "" if is_continue_story_content(content) else content
    return {
        "turn_id": make_id("turn"),
        "turn_number": len(campaign.get("turns", [])) + 1,
        "status": "active",
        "actor": actor,
        "player_id": player_id,
        "action_type": action_type,
        "input_text_raw": content,
        "input_text_display": input_text_display,
        "gm_text_raw": gm_text_display,
        "gm_text_display": gm_text_display,
        "requests": combined_requests,
        "patch": patch,
        "narrator_patch": narrator_patch,
        "extractor_patch": extractor_patch,
        "source_mode": action_type,
        "canon_applied": canon_applied,
        "attribute_profile": deep_copy(attribute_profile),
        "combat_resolution": deep_copy(combat_resolution),
        "resource_deltas_applied": deep_copy(resource_deltas_applied),
        "progression_events": deep_copy(progression_result.get("events") or []),
        "canon_gate": deep_copy(canon_gate_meta),
        "npc_updates": deep_copy(npc_updates),
        "codex_updates": deep_copy(codex_updates),
        "combat_meta": deep_copy(updated_combat),
        "state_before": deep_copy(state_before),
        "state_after": deep_copy(state_after),
        "retry_of_turn_id": retry_of_turn_id,
        "edited_at": None,
        "created_at": now,
        "updated_at": now,
        "edit_history": [],
        "prompt_payload": prompt_payload,
        "entity_guard": deep_copy(entity_guard or {"summary": {"total": 0}, "reports": []}),
    }
