from __future__ import annotations

from typing import Dict, Tuple


TURN_ENGINE_RUNTIME_DEPENDENCY_GROUPS: Dict[str, Tuple[str, ...]] = {
    "runtime_dependencies": (
        "make_id",
        "utc_now",
        "deep_copy",
        "LOGGER",
        "ERROR_CODE_TURN_INTERNAL",
        "ERROR_CODE_NARRATOR_RESPONSE",
        "ERROR_CODE_JSON_REPAIR",
        "ERROR_CODE_PATCH_SANITIZE",
        "ERROR_CODE_SCHEMA_VALIDATION",
        "ERROR_CODE_PATCH_APPLY",
        "ERROR_CODE_EXTRACTOR",
        "TURN_ERROR_USER_MESSAGES",
    ),
    "llm": (
        "call_ollama_json",
        "call_ollama_schema",
        "OLLAMA_TEMPERATURE",
        "OLLAMA_REPEAT_PENALTY",
        "MAX_TURN_MODEL_ATTEMPTS",
        "MIN_STORY_REWRITE_ATTEMPTS",
        "MAX_STORY_COMPRESS_ATTEMPTS",
        "STORY_REWRITE_SCHEMA",
    ),
    "extraction": (
        "build_extractor_context_packet",
        "call_canon_extractor",
        "call_npc_extractor",
        "apply_npc_upserts",
        "normalize_npc_codex_state",
    ),
    "turn_materialization": (
        "active_party",
        "active_turns",
        "blank_patch",
        "build_patch_summary",
        "campaign_slots",
        "current_turn",
        "display_name_for_slot",
        "is_continue_story_content",
        "merge_patch_payloads",
        "normalize_model_output_payload",
        "normalize_requests_payload",
        "remember_recent_story",
        "rebuild_memory_summary",
    ),
    "story_injection": (
        "SYSTEM_PROMPT",
        "TURN_MODE_GUIDE",
        "TURN_RESPONSE_JSON_CONTRACT",
        "CANON_EXTRACTOR_SYSTEM_PROMPT",
        "build_context_packet",
        "build_pacing_instruction_block",
        "is_suspicious_story_text",
        "ACTION_STOPWORDS",
        "ENGLISH_LANGUAGE_MARKERS",
        "GERMAN_LANGUAGE_MARKERS",
    ),
    "canon_progression": (
        "append_character_change_events",
        "apply_codex_triggers",
        "apply_progression_events",
        "apply_skill_events",
        "collect_codex_triggers",
        "run_canon_gate",
        "active_pacing_profile",
        "milestone_state_for_turn",
    ),
    "domain_helpers": (
        "apply_attribute_bias_to_patch",
        "apply_attribute_bias_to_resolution",
        "apply_combat_scaling_to_patch",
        "apply_skill_cost_deltas_to_patch",
        "apply_world_time_advance",
        "attribute_cap_for_campaign",
        "build_combat_scaling_context",
        "build_skill_system_requests",
        "canonical_resource_deltas_from_update",
        "canonical_resources_set_from_payload",
        "clean_auto_item_name",
        "clean_creator_item_name",
        "clean_scene_name",
        "clamp",
        "class_rank_sort_value",
        "compute_turn_budget_estimates",
        "default_class_current",
        "derive_attribute_relevance",
        "effective_skill_progress_multiplier",
        "ensure_character_progression_core",
        "ensure_class_rank_core_skills",
        "ensure_item_shape",
        "ensure_progression_shape",
        "infer_combat_context",
        "infer_item_slot_from_definition",
        "infer_skill_cost_deltas_from_text",
        "is_generic_scene_identifier",
        "is_plausible_scene_name",
        "is_skill_manifestation_name_plausible",
        "is_slot_id",
        "item_matches_equipment_slot",
        "legacy_misc_resource_deltas_from_update",
        "legacy_misc_resources_set_from_payload",
        "merge_dynamic_skill",
        "next_skill_xp_for_level",
        "normalize_ability_state",
        "normalize_attribute_influence_meta",
        "normalize_class_current",
        "normalize_dynamic_skill_state",
        "normalize_equipment_slot_key",
        "normalize_equipment_update_payload",
        "normalize_event_entry",
        "normalize_injury_state",
        "normalize_patch_semantics",
        "normalize_plotpoint_entry",
        "normalize_plotpoint_update_entry",
        "normalize_progression_event_list",
        "normalize_scar_state",
        "normalize_skill_elements_for_world",
        "normalize_skill_rank",
        "normalize_skill_store",
        "normalize_world_settings",
        "normalize_world_time",
        "normalized_eval_text",
        "rebuild_character_derived",
        "reconcile_canonical_resources",
        "resolve_class_element_id",
        "resolve_injury_healing",
        "resource_name_for_character",
        "skill_id_from_name",
        "slot_index",
        "strip_legacy_shadow_fields",
        "sync_scars_into_appearance",
        "update_combat_meta_after_turn",
        "update_turn_timing_ema",
        "write_legacy_shadow_fields",
        "ATTRIBUTE_KEYS",
        "DEFAULT_DYNAMIC_SKILL_LEVEL_MAX",
        "DEFAULT_NUMERIC_SKILL_DELTA_XP",
        "ENABLE_LEGACY_SHADOW_WRITEBACK",
        "INJURY_HEALING_STAGES",
        "INJURY_SEVERITIES",
        "PROGRESSION_SET_DIRECT_KEYS",
        "UNIVERSAL_SKILL_LIKE_NAMES",
    ),
    "campaign_lorus_defer": (
        "active_party",
        "active_turns",
        "campaign_slots",
        "display_name_for_slot",
        "remember_recent_story",
        "rebuild_memory_summary",
    ),
}


def dependency_names_for_group(group: str) -> Tuple[str, ...]:
    return TURN_ENGINE_RUNTIME_DEPENDENCY_GROUPS.get(group, ())


def all_dependency_names() -> Tuple[str, ...]:
    names = []
    seen = set()
    for group_names in TURN_ENGINE_RUNTIME_DEPENDENCY_GROUPS.values():
        for name in group_names:
            if name not in seen:
                names.append(name)
                seen.add(name)
    return tuple(names)
